<?xml version="1.0"?>

<!-- <!DOCTYPE invoice SYSTEM "contacts.dtd"> -->

<!DOCTYPE contacts [

  <!ELEMENT contacts (contact*)>
  <!ATTLIST contacts xmlns CDATA #REQUIRED>
  <!ATTLIST contacts xmlns:xsi CDATA #REQUIRED>
  <!ATTLIST contacts xmlns:person CDATA #REQUIRED>
  <!ATTLIST contacts xmlns:company CDATA #REQUIRED>
  <!ATTLIST contacts xsi:schemaLocation CDATA #REQUIRED>

  <!ELEMENT contact (
    ((person:name, person:surname) | company:name),
    address,
    (person:telephone | company:telephone),
    email
  )>

  <!ELEMENT person:name (#PCDATA)>
  <!ELEMENT person:surname (#PCDATA)>
  <!ELEMENT company:name (#PCDATA)>

  <!ELEMENT address (line1, line2, line3)>
  <!ELEMENT line1 (#PCDATA)>
  <!ELEMENT line2 (#PCDATA)>
  <!ELEMENT line3 (#PCDATA)>

  <!ELEMENT person:telephone (person:home, person:work, person:fax, person:mobile)>
  <!ELEMENT person:home (#PCDATA)>
  <!ELEMENT person:work (#PCDATA)>
  <!ELEMENT person:fax (#PCDATA)>
  <!ELEMENT person:mobile (#PCDATA)>


  <!ELEMENT company:telephone (company:office, company:fax)>
  <!ELEMENT company:office (#PCDATA)>
  <!ELEMENT company:fax (#PCDATA)>

  <!ELEMENT email (#PCDATA)>

]>

<contacts
  xmlns="http://www.w3schools.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:person="http://www.w3.org/person"
  xmlns:company="http://www.w3.org/company"
  xsi:schemaLocation="http://www.w3.org contacs.xsd">

  <contact>
    <person:name>John</person:name>
    <person:surname>Travolta</person:surname>
    <address>
      <line1>1, Some Street</line1>
      <line2>Some City</line2>
      <line3>WC1 5AB</line3>
    </address>
    <person:telephone>
      <person:home>02070000000</person:home>
      <person:work>02071111111</person:work>
      <person:fax>02072222222</person:fax>
      <person:mobile>07000000000</person:mobile>
    </person:telephone>
    <email>john@travolta.com</email>
  </contact>

  <contact>
    <person:name>Michelle</person:name>
    <person:surname>Pfeiffer</person:surname>
    <address>
      <line1>2, Some Street</line1>
      <line2>Some City</line2>
      <line3>WC1 5AB</line3>
    </address>
    <person:telephone>
      <person:home>02076666666</person:home>
      <person:work>02077777777</person:work>
      <person:fax>02078888888</person:fax>
      <person:mobile>07111111111</person:mobile>
    </person:telephone>
    <email>michelle@pfeiffer.com</email>
  </contact>

  <contact>
    <person:name>Michael</person:name>
    <person:surname>Keaton</person:surname>
    <address>
      <line1>3, Some Street</line1>
      <line2>Some City</line2>
      <line3>WC1 5AB</line3>
    </address>
    <person:telephone>
      <person:home>02079999999</person:home>
      <person:work>02080000000</person:work>
      <person:fax>02081111111</person:fax>
      <person:mobile>07222222222</person:mobile>
    </person:telephone>
    <email>michael@keaton.com</email>
  </contact>

  <contact>
    <person:name>Jennifer</person:name>
    <person:surname>Lawrence</person:surname>
    <address>
      <line1>1, Some Street</line1>
      <line2>Some City</line2>
      <line3>WC1 5AB</line3>
    </address>
    <person:telephone>
      <person:home>02082222222</person:home>
      <person:work>02083333333</person:work>
      <person:fax>02084444444</person:fax>
      <person:mobile>07333333333</person:mobile>
    </person:telephone>
    <email>jennifer@lawrence.com</email>
  </contact>

  <contact>
    <person:name>George</person:name>
    <person:surname>Clooney</person:surname>
    <address>
      <line1>1, Some Street</line1>
      <line2>Some City</line2>
      <line3>WC1 5AB</line3>
    </address>
    <person:telephone>
      <person:home>02085555555</person:home>
      <person:work>02086666666</person:work>
      <person:fax>02087777777</person:fax>
      <person:mobile>07444444444</person:mobile>
    </person:telephone>
    <email>george@clooney.com</email>
  </contact>

  <contact>
    <company:name>Apple</company:name>
    <address>
      <line1>1 Infinite Loop</line1>
      <line2>Cupertino</line2>
      <line3>CA 95014</line3>
    </address>
    <company:telephone>
      <company:office>08442090611</company:office>
      <company:fax>08442090612</company:fax>
    </company:telephone>
    <email>steve@apple.com</email>
  </contact>

  <contact>
    <company:name>Microsoft</company:name>
    <address>
      <line1>15010 Northeast 36th Street</line1>
      <line2>Redmond</line2>
      <line3>WA 98052</line3>
    </address>
    <company:telephone>
      <company:office>04257036214</company:office>
      <company:fax>04257036215</company:fax>
    </company:telephone>
    <email>bill@microsoft.com</email>
  </contact>

  <contact>
    <company:name>Google</company:name>
    <address>
      <line1>1, Mountain View</line1>
      <line2>San Francisco</line2>
      <line3>California</line3>
    </address>
    <company:telephone>
      <company:office>02070313000</company:office>
      <company:fax>02070313001</company:fax>
    </company:telephone>
    <email>sergey@google.com</email>
  </contact>

  <contact>
    <company:name>Canonical</company:name>
    <address>
      <line1>5th Floor, Blue Fin Building </line1>
      <line2>110 Southwark Street</line2>
      <line3>SE1 0SU</line3>
    </address>
    <company:telephone>
      <company:office>02076302400</company:office>
      <company:fax>02076302401</company:fax>
    </company:telephone>
    <email>mark@ubuntu.com</email>
  </contact>

  <contact>
    <company:name>Facebook</company:name>
    <address>
      <line1>1 Hacker Way</line1>
      <line2>Menlo Park</line2>
      <line3>94025</line3>
    </address>
    <company:telephone>
      <company:office>06505434800</company:office>
      <company:fax>06505434801</company:fax>
    </company:telephone>
    <email>mark@facebook.com</email>
  </contact>

</contacts>
