=== jbonigomes/xml/FMA/implementation/juices.xsd
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.w3schools.com"
  elementFormDefault="qualified"
  attributeFormDefault="qualified">

  <xs:element name="juices">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="type" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>

              <xs:element name="title" type="xs:token" maxOccurs="unbounded"/>

              <xs:element name="juice" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>

                    <xs:element name="name" type="xs:token"/>
                    <xs:element name="description" type="xs:token"/>

                    <xs:element name="ingredients">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ingredient" type="xs:token" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="information">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="blend" type="xs:token"/>
                          <xs:element name="concentrate">
                            <xs:simpleType>
                              <xs:restriction base="xs:token">
                                <xs:enumeration value="Yes"/>
                                <xs:enumeration value="No"/>
                              </xs:restriction>
                            </xs:simpleType>
                          </xs:element>
                          <xs:element name="vitamins">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="vitamin" type="xs:token" maxOccurs="unbounded"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="nutricional">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="kj" type="xs:integer"/>
                          <xs:element name="kcal" type="xs:integer"/>
                          <xs:element name="carbohydrate" type="xs:integer"/>
                          <xs:element name="sugars" type="xs:integer"/>
                          <xs:element name="salt" type="xs:integer"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>

                    <xs:element name="price">
                      <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                          <xs:fractionDigits value="2"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                  </xs:sequence>
                  <xs:attribute name="id" type="xs:integer" />
                </xs:complexType>
              </xs:element>

            </xs:sequence>
            <xs:attribute name="id" type="xs:integer" />
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>

    <xs:unique name="unique-type-id">
      <xs:selector xpath="type"/>
      <xs:field xpath="@id"/>
    </xs:unique>

    <xs:unique name="unique-juice-id">
      <xs:selector xpath="type/juice"/>
      <xs:field xpath="@id"/>
    </xs:unique>

  </xs:element>
</xs:schema>

=== jbonigomes/xml/FMA/implementation/juices.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="juices.xsl"?>

<!DOCTYPE juices []>

<juices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://titan.dcs.bbk.ac.uk/~jgomes01/xmfma juices.xsd">

  <type id="1">
    <title>Fruit Juices</title>
    <juice id="1">
      <name>Mango Tango</name>
      <description>
        Bursting with an unbelievable mango flavour this juice will wake even
        the most tired sleeper from their slumbers. Mango Tango is packed with
        vitamins.
      </description>
      <ingredients>
        <ingredient>Mango</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Mango</blend>
        <concentrate>No</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
          <vitamin>C</vitamin>
        </vitamins>
      </information>
      <nutricional>
        <kj>250</kj>
        <kcal>65</kcal>
        <carbohydrate>16</carbohydrate>
        <sugars>14</sugars>
        <salt>1</salt>
      </nutricional>
      <price>10</price>
    </juice>

    <juice id="2">
      <name>Strawberry Larry</name>
      <description>
        Bursting with an unbelievable strawberry flavour this juice will wake
        even the most tired sleeper from their slumbers. Strawberry Larry is
        packed with vitamins.
      </description>
      <ingredients>
        <ingredient>Strawberry</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Strawberry</blend>
        <concentrate>Yes</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
          <vitamin>C</vitamin>
        </vitamins>
      </information>
      <nutricional>
        <kj>250</kj>
        <kcal>65</kcal>
        <carbohydrate>16</carbohydrate>
        <sugars>14</sugars>
        <salt>0.5</salt>
      </nutricional>
      <price>12</price>
    </juice>

    <juice id="3">
      <name>Orange Memorange</name>
      <description>
        Bursting with an unbelievable orange flavour this juice will wake even
        the most tired sleeper from their slumbers. Orange Memorange is packed
        with vitamins.
      </description>
      <ingredients>
        <ingredient>Orange</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Orange</blend>
        <concentrate>No</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
          <vitamin>C</vitamin>
        </vitamins>
      </information>
      <nutricional>
        <kj>250</kj>
        <kcal>65</kcal>
        <carbohydrate>16</carbohydrate>
        <sugars>14</sugars>
        <salt>0</salt>
      </nutricional>
      <price>14</price>
    </juice>
  </type>

  <type id="2">
    <title>Berry Juices</title>
    <juice id="4">
      <name>Lemon Cannon</name>
      <description>
        Bursting with an unbelievable lemon flavour this juice will wake even
        the most tired sleeper from their slumbers. Lemon Cannon is packed with
        vitamins.
      </description>
      <ingredients>
        <ingredient>Lemon</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Lemon</blend>
        <concentrate>Yes</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
          <vitamin>C</vitamin>
        </vitamins>
      </information>
      <nutricional>
        <kj>250</kj>
        <kcal>65</kcal>
        <carbohydrate>16</carbohydrate>
        <sugars>14</sugars>
        <salt>1</salt>
      </nutricional>
      <price>10</price>
    </juice>

    <juice id="5">
      <name>Pomegranate Grenade</name>
      <description>
        Bursting with an unbelievable pomegranate flavour this juice will wake
        even the most tired sleeper from their slumbers. Pomegranate Grenade is
        packed with vitamins.
      </description>
      <ingredients>
        <ingredient>Pomegranate</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Pomegranate</blend>
        <concentrate>No</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
          <vitamin>C</vitamin>
        </vitamins>
      </information>
      <nutricional>
        <kj>250</kj>
        <kcal>65</kcal>
        <carbohydrate>16</carbohydrate>
        <sugars>14</sugars>
        <salt>0.5</salt>
      </nutricional>
      <price>12</price>
    </juice>

    <juice id="6">
      <name>Kiwi Mewe</name>
      <description>
        Bursting with an unbelievable kiwi fruit flavour this juice will wake
        even the most tired sleeper from their slumbers. Kiwi Mewe is packed
        with vitamins.
      </description>
      <ingredients>
        <ingredient>Kiwi</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Kiwi</blend>
        <concentrate>Yes</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
          <vitamin>C</vitamin>
        </vitamins>
      </information>
      <nutricional>
        <kj>250</kj>
        <kcal>65</kcal>
        <carbohydrate>16</carbohydrate>
        <sugars>14</sugars>
        <salt>0</salt>
      </nutricional>
      <price>14</price>
    </juice>
  </type>

  <type id="3">
    <title>Vegetable Juices</title>
    <juice id="7">
      <name>Satsuma Puma</name>
      <description>
        Bursting with an unbelievable satsuma flavour this juice will wake even
        the most tired sleeper from their slumbers. Satsuma Puma is packed with
        vitamins.
      </description>
      <ingredients>
        <ingredient>Satsuma</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Satsuma</blend>
        <concentrate>No</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
          <vitamin>C</vitamin>
        </vitamins>
      </information>
      <nutricional>
        <kj>250</kj>
        <kcal>65</kcal>
        <carbohydrate>16</carbohydrate>
        <sugars>14</sugars>
        <salt>1</salt>
      </nutricional>
      <price>10</price>
    </juice>

    <juice id="8">
      <name>Passion Fashion</name>
      <description>
        Bursting with an unbelievable passion fruit flavour this juice will wake
        even the most tired sleeper from their slumbers. Passion  Fashion is
        packed with vitamins.
      </description>
      <ingredients>
        <ingredient>Passion fruit</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Passion fruit</blend>
        <concentrate>Yes</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
          <vitamin>C</vitamin>
        </vitamins>
      </information>
      <nutricional>
        <kj>250</kj>
        <kcal>65</kcal>
        <carbohydrate>16</carbohydrate>
        <sugars>14</sugars>
        <salt>0.5</salt>
      </nutricional>
      <price>12</price>
    </juice>

    <juice id="9">
      <name>Red Apple</name>
      <description>
        Bursting with an unbelievable red apple flavour this juice will wake
        even the most tired sleeper from their slumbers. Red Apple is packed
        with vitamins.
      </description>
      <ingredients>
        <ingredient>Red apple</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Red apple</blend>
        <concentrate>No</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
          <vitamin>C</vitamin>
        </vitamins>
      </information>
      <nutricional>
        <kj>250</kj>
        <kcal>65</kcal>
        <carbohydrate>16</carbohydrate>
        <sugars>14</sugars>
        <salt>0</salt>
      </nutricional>
      <price>14</price>
    </juice>
  </type>

  <type id="4">
    <title>Health Juices</title>
    <juice id="10">
      <name>Green Apple</name>
      <description>
        Bursting with an unbelievable green apple flavour this juice will wake
        even the most tired sleeper from their slumbers. Green Apple is
        packed with vitamins.
      </description>
      <ingredients>
        <ingredient>Green apple</ingredient>
        <ingredient>Colorant</ingredient>
        <ingredient>Water</ingredient>
        <ingredient>Caffeine</ingredient>
        <ingredient>Sugar</ingredient>
      </ingredients>
      <information>
        <blend>Green apple</blend>
        <concentrate>Yes</concentrate>
        <vitamins>
          <vitamin>A</vitamin>
          <vitamin>B</vitamin>
