=== jbonigomes/xml/Session_3/HO/Products.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!ELEMENT products (product*)>
	<!ELEMENT product (name | description | price | contract?)>
	<!ATTLIST photoItem id ID #REQUIRED>
	<!ELEMENT name (#PCDATA)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT price (currency | amount)>
	<!ELEMENT currency (£ | € | $) "£">
	<!ELEMENT amount (#PCDATA)>
	<!ELEMENT contract (option*)>
	<!ATTLIST photoItem
		min CDATA #REQUIRED
		max CDATA #REQUIRED
		durationtype (day | week | month | year) "day"
	>
	<!ELEMENT option (#PCDATA)>

=== jbonigomes/xml/Session_3/HO/Products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE products SYSTEM "products.dtd">
<products>
	<product id="12344"> 
		<name>Orange SPV</name>
		<description>Orange WAP phone</description>
		<price>	
			<currency>£</currency>
			<amount>123.23</amount>
		</price>
		<contract min="3" max="12" durationtype="month">
			<option>Lost and stolen insurance</option>
			<option>Free replacement if damaged</option>
		</contract>
	</product>
	<product id="125674">
		<name>Sony Ericsson</name>
		<description>Walkman</description>
		<price>
			<currency>£</currency>
			<amount>199.00</amount>
		</price>
	</product>
	<product id="123444">
		<name>Apple Macbook Air</name>
		<description>Notebook</description>
		<price>
			<currency>£</currency>
			<amount>800.00</amount>
		</price>
		<contract min="3" max="12" durationtype="month">
			<option>Free replacement if damaged</option>
		</contract>
	</product>
	<product id="123555">
		<name>Apple Macbook Pro</name>
		<description>Notebook</description>
		<price>
			<currency>£</currency>
			<amount>1000.00</amount>
		</price>
	</product>
</products>
