=== jbonigomes/xml/Session_3/HO/ProjectTimesheets.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!ELEMENT timesheets (employee, projects+)>
	<!ELEMENT employee (firstname, surname)>
	<!ATTLIST employee
		id ID #REQUIRED
		ismanager (true | false) "false"
		hiredate CDATA #REQUIRED
	>
	<!ELEMENT firstname (#PCDATA)>
	<!ELEMENT surname (#PCDATA)>
	<!ELEMENT projects (project+)>
	<!ELEMENT project (task+)>
	<!ATTLIST project code ID #REQUIRED>
	<!ELEMENT task (description, duration)>
	<!ELEMENT description (#PCDATA)>
	<!ELEMENT duration (planned, actual)>
	<!ATTLIST duration type (days | hours) "hours">
	<!ELEMENT planned (#PCDATA)>
	<!ELEMENT actual (#PCDATA)>

=== jbonigomes/xml/Session_3/HO/ProjectTimesheets.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE products SYSTEM "ProjectTimesheets.dtd">

<!-- <!DOCTYPE timesheets [

]> -->

<timesheets>
	<employee id="A234456" ismanager="false" hiredate="12/01/2003">
		<firstname>Julie</firstname>
		<surname>Smith</surname>
	</employee>
	<projects>
		<project code="TSK2367">
			<task>
				<description>Create project plan for MIJ website</description>
				<duration type="days">
					<planned>2</planned>
					<actual>1</actual>
				</duration>
			</task>
			<task>
				<description>Draft the conceptual web site navigation for MIJ</description>
				<duration type="hours">
					<planned>3</planned>
					<actual>2</actual>
				</duration>
			</task>
		</project>
	</projects>
</timesheets>
