=== jbonigomes/xml/Session_4/HO/products.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
  xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.dcs.bbk.ac.uk/ns"
  elementFormDefault="qualified">

  <element name="products">
    <complexType>
      <sequence>
        <element name="product">
          <complexType>
            <sequence>
              <element name="name" type="string" />
              <element name="description" type="string">
              <element name="price">
                <complexType>
                  <sequence>
                    <element name="currency" type="token" />
                    <element name="amount" type="decimal" />
                  </sequence>
                </complexType>
              </element>
              <element name="contract">
                <complexType>
                  <sequence>
                    <element name="option" type="string" />
                  </sequence>
                  <attribute name="min" type="positiveInteger" />
                  <attribute name="max" type="positiveInteger" />
                  <attribute name="durationtype" type="string" />
                </complexType>
              </element>
            </sequence>
            <attribute name="id" type="token" />
          </complexType>
        </element>
      </sequence>
    </complexType>
  </element>

</schema>

=== jbonigomes/xml/Session_4/HO/products.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- <!DOCTYPE products [

]> -->

<products
  xmlns="http://www.w3schools.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.w3schools.com products.xsd">

  <product id="12344">
    <name>Orange SPV</name>
    <description>Orange WAP phone</description>
    <price>
      <currency>£</currency>
      <amount>123.23</amount>
    </price>
    <contract min="3" max="12" durationtype="month">
      <option>Lost and stolen insurance</option>
      <option>Free replacement if damaged</option>
    </contract>
  </product>

  <product id="125674">
    <name>Sony Ericsson</name>
    <description>Walkman</description>
    <price>
      <currency>£</currency>
      <amount>199.00</amount>
    </price>
  </product>

  <product id="12355">
    <name>Apple Inc</name>
    <description>iPhone</description>
    <price>
      <currency>£</currency>
      <amount>300.00</amount>
    </price>
    <contract min="3" max="12" durationtype="month">
      <option>Lost and stolen insurance</option>
      <option>Free replacement if damaged</option>
    </contract>
  </product>

  <product id="12355">
    <name>Apple Inc</name>
    <description>iPad</description>
    <price>
      <currency>£</currency>
      <amount>300.00</amount>
    </price>
  </product>
</products>
